In [4]:
import pandas as pd
import numpy as np
from datetime import datetime

dados = pd.DataFrame({'col A' : [1,2,3,4,5,6,np.nan],
                      'col B' : ['a',np.nan,'c','d',np.nan,'e','f'],
                      'col C' : ["NaN",True,False,True,True,False,True],
                      'col D' : [datetime.now(),datetime.now(),np.nan,datetime.now(),datetime.now(),datetime.now(),datetime.now()]})

dados.fillna("NaN", inplace = True)
dados

  col A col B  col C                      col D
0   1.0     a    NaN 2022-03-04 22:35:23.615975
1   2.0   NaN   True 2022-03-04 22:35:23.615975
2   3.0     c  False                        NaT
3   4.0     d   True 2022-03-04 22:35:23.615975
4   5.0   NaN   True 2022-03-04 22:35:23.615975
5   6.0     e  False 2022-03-04 22:35:23.615975
6   NaN     f   True 2022-03-04 22:35:23.615975

In [2]:
dados = pd.DataFrame({'col A' : [1,2,3,4,5,6,np.nan],
                      'col B' : ['a',np.nan,'c','d',np.nan,'e','f'],
                      'col C' : [np.nan,True,False,True,True,False,True],
                      'col D' : [datetime.now(),datetime.now(),np.nan,datetime.now(),datetime.now(),datetime.now(),datetime.now()]})

dados['col B'].fillna(0, inplace = True)
dados

   col A col B  col C                      col D
0    1.0     a    NaN 2022-03-04 22:34:15.319821
1    2.0     0   True 2022-03-04 22:34:15.319821
2    3.0     c  False                        NaT
3    4.0     d   True 2022-03-04 22:34:15.319821
4    5.0     0   True 2022-03-04 22:34:15.319821
5    6.0     e  False 2022-03-04 22:34:15.319821
6    NaN     f   True 2022-03-04 22:34:15.319821